---
- hosts: localhost
  connection: local 
  become: yes 

  pre_tasks:
  - name: Apply Updates (CentOS)
    dnf: 
      update_cache: yes
      update_only: yes
    when: ansible_distribution == 'CentOS'

  - name: Apply Updates (Ubuntu)
    apt: 
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  tasks: 
    - include: tasks/packages.yml
    - include: tasks/new_user.yml
