---
- hosts: localhost
  connection: local 
  become: yes 

  tasks:
  - name: Apply Updates 
    dnf: 
      update_cache: yes
      update_only: yes

  - name: Install htop
    dnf: 
      name: htop
      

