---
- hosts: localhost
  connection: local 
  become: yes 

  pre_tasks:
  - name: Apply Updates 
    dnf: 
      update_cache: yes
      update_only: yes

  tasks: 
    - include: tasks/packages.yml
    - include: tasks/new_user.yml
