- name: Install packages (CentOS)
  dnf: 
    name:
      - htop
      - tmux
      - mc 
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Install packages (Ubuntu)
  apt: 
    name:
      - htop
      - tmux
      - mc 
      - net-tools
  when: ansible_distribution == 'Ubuntu'
